title: "pusti's website"
author: "pusti"
description: "uw madison cs/ds; aspiring asparagus hater"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "reading list !", url: "https://www.goodreads.com/user/show/180742112-pusti"}
  - {title: "upl", url: "https://www.upl.cs.wisc.edu"}
  - {title: "thoughts" , file: "thoughts.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jesrani@wisc.edu"}
  - {title: Github, icon: github, url: "https://github.com/voldemozzerella"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
